create order summary component
optimumBA/frontend_mentor_challenges pull request #123
Opened 2023-05-12 14:21 UTC by jrowah

Edit files to achieve both desktop and mobile component designs of challenge.
Desktop design:
![image](https://github.com/optimumBA/frontend_mentor_challenges/assets/76947107/23384f5c-8580-48be-a63b-472ac7d438d9)

Mobile Design:
![image](https://github.com/optimumBA/frontend_mentor_challenges/assets/76947107/32b2aae9-3d86-4f52-8a6d-9582acb08fa1)

2023-05-16 20:30 UTC, almirsarajcic requested changes
Extra images. Otherwise, looks good!

2023-05-20 10:34 UTC, almirsarajcic requested changes
There are still unnecessary icons in the PR.

2023-05-21 10:58 UTC, rowah commented
> There are still unnecessary icons in the PR.

I have removed the unnecessary icons.

2023-05-27 07:13 UTC, almirsarajcic approved these changes

2024-12-16 17:18 UTC, closed without merging