Stats preview card component
optimumBA/frontend_mentor_challenges pull request #91
Opened 2022-12-03 11:20 UTC by amos-kibet

- [ ] Style according to design
- [ ] Write correct commit messages
- [ ] Ensure tests are passing

2022-12-05 08:07 UTC, almirsarajcic approved these changes

2023-01-17 11:16 UTC, amos-kibet commented
Reopened, and as well not sure if it passes the checks

2023-01-17 11:24 UTC, almirsarajcic requested changes
Images should be inside `challenges/stats_preview_card_component/images` directory.

2023-01-17 12:37 UTC, amos-kibet commented
I should delete this PR. I lost these files. I am opening a new one.

2023-01-17 12:37 UTC, closed without merging