Qr code component
optimumBA/frontend_mentor_challenges pull request #96
Opened 2022-12-07 09:17 UTC by amos-kibet

Rework of the challenge.
Nothing changed, except for the commit messages.

2022-12-07 11:00 UTC, almirsarajcic requested changes
Some image is missing or the path is incorrect.
Take a look at the tests.

2022-12-08 07:58 UTC, almirsarajcic requested changes
Bring back the `screenshots/.gitkeep` file.
Tests are failing because it's missing.

2022-12-08 09:14 UTC, amos-kibet commented
I have removed screenshots folder from .gitignore. 

It was ignored by default, not by me.

2022-12-08 09:21 UTC, amos-kibet commented
New learning: I now understand the reason why I always see empty folders having .gitkeep files. git docs say that it only tracks files, so empty folders won't be tracked. Putting an empty .gitkeep file helps to make the folder be tracked by git.

2022-12-08 09:56 UTC, almirsarajcic requested changes
You shouldn't commit files in screenshots directory.
Check the diff - it should reflect only the changes in challenges/qr_code_component directory.

2022-12-08 09:56 UTC, almirsarajcic commented on .gitignore
> -!/screenshots/.gitkeep
You're not supposed to change `.gitignore` file.

2022-12-08 10:49 UTC, amos-kibet commented on .gitignore
> -!/screenshots/.gitkeep
Okay, I missed that. Let me revert.

2022-12-08 10:57 UTC, amos-kibet commented on .gitignore
> -!/screenshots/.gitkeep
Should I keep `!/screenshots/.gitkeep` line in .gitignore?

2022-12-08 15:54 UTC, amos-kibet commented
@almirsarajcic I think I have fixed it. Kindly check.

2022-12-09 09:06 UTC, almirsarajcic requested changes
Now there are even more changes in the diff.

2022-12-10 07:06 UTC, closed without merging